### ISSUE TITLE
__multicall__ deprecated

### ISSUE THREAD

**Issue by The-Compiler** [manahl/pytest-plugins#11]
I saw this when using profiling, but maybe it's a problem with other plugins as well, I don't know.

`__multicall__` is slanted for removal and has been deprecated for pytest 2.8, but the plugin still uses it:

```
WI1 .../lib/python3.5/site-packages/pytest_profiling.py:47 'pytest_pyfunc_call' hook uses deprecated __multicall__ argument
```

**Comment by eeaston** [comment]
Thanks for raising this!  I was just about to open the issue myself and you have helpfully done so already :)

**Comment by dylanninin** [comment]
Just a mark.

-- 
```python

platform darwin -- Python 3.5.0, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
benchmark: 3.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=5.00us max_time=1.00s calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: xxxx, inifile:
plugins: benchmark-3.0.0, cov-2.2.1, instafail-0.3.0, profiling-1.1.1


warnings:

.virtualenvs/openplay3/lib/python3.5/site-packages/pytest_profiling.py:59 'pytest_pyfunc_call' hook uses deprecated __multicall__ argument
```

**Comment by bsergean** [comment]
Hi there, I'm also getting this warning, but on top of that my prof folder is empty ... I cannot get the module to work essentially with my code base. Not sure what I'm doing wrong.

    'pytest_pyfunc_call' hook uses deprecated __multicall__ argument

**Comment by ssbarnea** [comment]
Nice to see a working PR made against this bug. Let's hope we'll see the fix published on PYPI soon.

**Comment by bmoscon** [comment]
merged
