### ISSUE TITLE
Please include wheels for modern Pythons

### ISSUE THREAD

**Issue by jaraco** [manahl/pytest-plugins#125]
It seems that pytest-virtualenv (and possibly other plugins) are released as Python 2 only wheels. I suspect these plugins are pure-python, version-agnostic packages, so wheels should be released as universal wheels.

Not releasing wheels means that a package must build the package from a source dist, which causes `setup_requires=['setuptools-git']` to invoke easy_install, which fails on some builds of Python (including official builds of Python 3.5 for macOS, which were built against older versions of OpenSSL without TLS 1.2 support), so fail to load packages from PyPI via easy_install.

**Comment by quartox** [comment]
Another solution (which might be simpler) would be to include a pyproject.toml (see [pep 518](https://www.python.org/dev/peps/pep-0518/)) which allows pip to install `setup_requires` before opening the `setup.py`.

**Comment by jaraco** [comment]
Yes. In my opinion, both should be done.

**Comment by eeaston** [comment]
Hi, we just merged #130 which should address this, we'll get a release out very soon thanks!

**Comment by eeaston** [comment]
Released in 1.7.0 - many apologies all for the delay in releasing to pypi.
