### ISSUE TITLE
there is no new releases on PyPI

### ISSUE THREAD

**Issue by chinskiy** [manahl/pytest-plugins#129]
Hi!
I see in github [releases](https://github.com/manahl/pytest-plugins/releases
) that last release is 1.6.2 but on [PyPI](https://pypi.org/project/pytest-profiling/#history
) last release is 1.6.0
would be cool to have latest release on PyPI also

**Comment by bmoscon** [comment]
https://pypi.org/project/pytest-server-fixtures/ shows 1.6.2

**Comment by bmoscon** [comment]
going by the change log:

https://github.com/manahl/pytest-plugins/blob/master/CHANGES.md

nothing has changed since 1.6.0 except the server fixtures, so maybe thats why nothing else was released (no changes to them)

**Comment by chinskiy** [comment]
Ohhh I see, you right!
Thanks for fast answer, closing
