### ISSUE TITLE
pytest-virtualenv doesn't work on Python 3.4

### ISSUE THREAD

**Issue by rutsky** [manahl/pytest-plugins#13]
Packages `pytest-virtualenv` is being installed normally, but `py.test --fixtures` doesn't list `virtualenv`.

**Comment by rutsky** [comment]
#14 fixes this issue.

**Comment by eeaston** [comment]
Hi, thanks for raising - this was rolled into #16 yeah?

**Comment by rutsky** [comment]
> Hi, thanks for raising - this was rolled into #16 yeah?

Yes. I use version combined from #16 and #18 to run `pytest-virtualenv` on Python 2 and 3 in [setuptools-trial](https://github.com/rutsky/setuptools-trial): https://github.com/rutsky/pytest-plugins/tree/python3-bundled-windows

**Comment by eeaston** [comment]
Hi there, this should be finally all sorted out by #33, I'll get a release out today.

**Comment by eeaston** [comment]
Fixed in v1.2.2

**Comment by rutsky** [comment]
@eeaston thanks!
