### ISSUE TITLE
pytest-server-fixture: Update RethinkDB fixtures to support rethinkdb >= 2.4.0

### ISSUE THREAD

**Issue by jcfr** [manahl/pytest-plugins#132]
Problem: Using the latest version of the python package causes the `tests/integration/test_rethink_server.py` to fail.

Background: Since the API associated with the latest release of [rethinkdb-python](https://github.com/rethinkdb/rethinkdb-python) package [released on March 2nd 2019](https://pypi.org/project/rethinkdb/#history) is backward incompatible, the implementation of the [RethinkDB fixtures](https://github.com/manahl/pytest-plugins/tree/master/pytest-server-fixtures#rethinkdb) need to be updated.

See https://github.com/rethinkdb/rethinkdb-python/releases/tag/v2.4.0

**Comment by eeaston** [comment]
Thanks for raising - gosh I'm surprised the driver was updated since the database itself has ceased supported development a few years ago now.

**Comment by eeaston** [comment]
Ah - @jcfr I just spotted you removed egg support. I'm afraid I'll have to put this back as it's needed for our company's internal build (we still use eggs, for various Reasons).

**Comment by eeaston** [comment]
Fixed in #134
