### ISSUE TITLE
pytest-profiling requirements

### ISSUE THREAD

**Issue by jhagege** [manahl/pytest-plugins#133]
Hi, I noticed pytest-profiling requires pytest < 4.0.0 
```
install_requires = ['six',
                    'pytest<4.0.0',
                    'gprof2dot',
                    ]
```

Is there a way to make it compatible with latest versions of pytest ? 
Thanks !

**Comment by bmoscon** [comment]
there is already a pr open for this I believe

**Comment by eeaston** [comment]
Hiya, support for the latest pytest has been merged in now, we'll get a release out very soon, thanks!
