### ISSUE TITLE
Publish new version of pytest-verbose-parametrize to PyPI plz

### ISSUE THREAD

**Issue by webknjaz** [manahl/pytest-plugins#137]
The currently published one doesn't work with `pytest >= 4.0.0`

**Comment by webknjaz** [comment]
cc @eeaston @javefang ^

**Comment by saznetro** [comment]
Would be nice to have also the pytest-profiling to be released as well in pypi to have this fix. I guess it applies for all the plugins.

**Comment by decentral1se** [comment]
Hi there folks, this would be great to see happen. 

Anything that can be done to push this along?

**Comment by beamerkun** [comment]
+1 to the request, would love to use some of the plugins but the `pytest < 4.0.0` blocks me ;-(

Any dates for the release?

**Comment by eeaston** [comment]
1.7.0 released - many apologies all for the huge delay guys!
