### ISSUE TITLE
Async tests with rethinkdb

### ISSUE THREAD

**Issue by skolsuper** [manahl/pytest-plugins#17]
First, thanks very much for sharing this package, it's awesome!

I am currently trying to test a tornado app with rethink, however there is no hook to call the `rethinkdb.set_loop_type` method before creating a connection.  It would be cool if you could add something.

If not, I will try to set aside some time in a couple of weeks and contribute a PR.  Any advice/pointers on implementation would be appreciated.

**Comment by eeaston** [comment]
Hi there, good suggestion thanks!
There's a number of ways we could do this, but how I'd do it is something like:
Add a config variable in pytest_server_fixtures.__init__:
```
DEFAULT_SERVER_FIXTURES_RETHINK_LOOP_TYPE = None
CONFIG=FixtureConfig(
  ..
  rethink_loop_type==os.getenv('SERVER_FIXTURES_RETHINK_LOOP_TYPE', DEFAULT_SERVER_FIXTURES_RETHINK_LOOP_TYPE),
  ... 
)
```

Add a constructor argument to the RethinkDBServer class:
    
```
class RethinkDBServer(TestServer):
    random_port = True

    def __init__(self, loop_type=CONFIG.rethink_loop_type, **kwargs):
        global rethinkdb
        try:
            import rethinkdb
        except ImportError:
            pytest.skip('rethinkdb not installed, skipping test')
        super(RethinkDBServer, self).__init__(**kwargs)
        if loop_type:
           rethinkdb.set_loop_type(loop_type)
            
```

Then, you could enable tornado by either setting the environment variable before running your test, setting the config options manually in the Python, or constructing your own fixture with the class directly.

**Comment by eeaston** [comment]
@skolsuper Hi there, with the sad news recently of the demise of RethinkDB, do you think you will still be working on this issue? Otherwise I will close it, thanks.

**Comment by jamesabc** [comment]
Hi @eeaston, I apologize, I had forgotten all about this issue as I am not working with Python much any more :(.  It is a shame about rethinkdb the company, but I imagine the database might live on for a while.  Then again, if nobody else has had this issue maybe it's just not a common combination, and I doubt anybody is about to pick it up now, so I think you can safely just close this :(

**Comment by skolsuper** [comment]
Hi @eeaston, I apologize, I had forgotten all about this issue as I am not working with Python much any more :(. It is a shame about rethinkdb the company, but I imagine the database might live on for a while. Then again, if nobody else has had this issue maybe it's just not a common combination, and I doubt anybody is about to pick it up now, so I think you can safely just close this :(
