### ISSUE TITLE
python3 can't find pytest_shutils' Workspace?

### ISSUE THREAD

**Issue by go-bears** [manahl/pytest-plugins#23]
We're using pytest_shutils Workspace for integration testing but our build fails Travis CI on python 3.5 where it passes with Python 2.7.  The error is that python 3 can't find cmdline and can't import Workspace. Is python3.5 incompatibility with pytest_shutils a currently known issue? 

![python3_pytest_shutil_error](https://cloud.githubusercontent.com/assets/6887377/17792806/df715136-6557-11e6-8980-b54caa2ac076.png)

**Comment by go-bears** [comment]
@arbonap @singingwolfboy is this an accurate description of the problem with Travis and Lektor tests?

**Comment by singingwolfboy** [comment]
@go-bears: looks like this was fixed in this commit: https://github.com/manahl/pytest-plugins/commit/f76dc8b8430be8afc5e2792baf3afb3f94483e8d Can you try again now?

**Comment by jcfr** [comment]
I confirm that f76dc8b allows the use of pytest_shutils with py3 :+1:

**Comment by jcfr** [comment]
would it make sense to do an other minor release ?

**Comment by go-bears** [comment]
@jcfr That would be wonderful!

**Comment by jcfr** [comment]
>>  do an other minor release

> That would be wonderful!

@go-bears  Glad to know we are on the same page, then do you know who should be contacted to create the release ?

**Comment by bmoscon** [comment]
We'll be doing a new release soon, thanks for your patience! @eeaston

**Comment by eeaston** [comment]
Hi, this should be fixed now by #33 in the next release which I'll get to today.

**Comment by eeaston** [comment]
Fixed in v1.2.2

**Comment by jcfr** [comment]
Great news :+1:  Thanks for moving this forward.
