### ISSUE TITLE
Tearing down a workspace can raise errors

### ISSUE THREAD

**Issue by Daenyth** [manahl/pytest-plugins#24]
If the server you're running removes files from inside the workspace dir when it's killed (like pid files, log files, sockets, etc), then the call to `shutil.rmtree` can raise exceptions. It appears that it's a race condition; rmtree lists all the files and then remove them, and in between the list and remove, the file can be removed by another process.

Passing `ignore_errors=True` should be enough to handle this. I've done this manually in my code by overriding `teardown` and it seems to work fine.

If you'd like that as a default I can put in a PR for it.

This is specifically problematic because it results in pytest reporting a failure, which fails our CI build.

**Comment by eeaston** [comment]
Good spot - fixed in fbf566a

**Comment by eeaston** [comment]
Fixed in v1.2.2
