### ISSUE TITLE
Missing 'request' argument for python3.5

### ISSUE THREAD

**Issue by dusktreader** [manahl/pytest-plugins#25]
The virtualenv fixture isn't working for me with python3.5 and pytest 3.0.2

```
fixturefunc = <function virtualenv at 0x105c15a60>
request = <SubRequest 'virtualenv' for <Function 'test_go'>>, kwargs = {}

    def call_fixture_func(fixturefunc, request, kwargs):
        yieldctx = is_generator(fixturefunc)
        if yieldctx:
>           it = fixturefunc(**kwargs)
E           TypeError: wrapper() missing 1 required positional argument: 'request'

../.virtualenvs/dot/lib/python3.5/site-packages/_pytest/fixtures.py:689: TypeError
```

**Comment by bmoscon** [comment]
thanks for opening this, I'll try and reproduce this sometime over the next week and then issue a fix

**Comment by bmoscon** [comment]
@dusktreader  with the latest release a lot of changes went into the codebase, and the tests run in 2.7, 3.4 and 3.5. You should try it out and let us know if its still not working for you.

**Comment by dusktreader** [comment]
@bmoscon I'll try to test this out soon, but I'm not actively working on that code right now, so it might be a while.

**Comment by bmoscon** [comment]
as far as I've determined (via local testing) this is now fixed. Please let me know if this is not the case and re-open the issue.
