### ISSUE TITLE
Rethink fixture breaks on python3

### ISSUE THREAD

**Issue by Daenyth** [manahl/pytest-plugins#26]
```
  File "/Users/daenyth/project/lib/python3.5/site-packages/pytest_server_fixtures/rethink.py", line 94
    except rethinkdb.errors.RqlRuntimeError, err:
                                           ^
SyntaxError: invalid syntax
```

**Comment by Daenyth** [comment]
Actually it looks like this is fixed in git but hasn't been release to pypi yet.

**Comment by Daenyth** [comment]
I'm also having trouble getting pip to install from git, since the repo has bundled many plugins together - normally you can grab a zip of some commit, but there's not just the server fixtures. @eeaston could we get a new version put onto pypi please?

**Comment by bmoscon** [comment]
We'll be working on this soon!

**Comment by Daenyth** [comment]
I think this is fixed in the unmerged python 3 pull request

**Comment by bmoscon** [comment]
yes, my edit clarified that I didn't mean fixing this, but releasing a new version (which has the fix in it already)

**Comment by Daenyth** [comment]
Either that or merged but not released to pypi

**Comment by eeaston** [comment]
Fixed in #33

**Comment by eeaston** [comment]
Sorry, I'll only close this issue once the release is done

**Comment by eeaston** [comment]
Release done, this should be fixed now.

**Comment by Daenyth** [comment]
That's good :+1:
