### ISSUE TITLE
pstats data not created and setup.py fails to install

### ISSUE THREAD

**Issue by asfaltboy** [manahl/pytest-plugins#4]
Thanks open sourcing the plugin. However, however I tried, I could not make it run as intended.
## Broken `setup.py`

I could not install the plugin by running "setup.py sdist install". That is, the installation did not fail, but running `py.test --profile` failed with `ImportError: No module named pytest_profiling`. Indeed `pytest_profiling.py` was nowhere to be found in my virtualenv dir.

This happens, I believe, since [setuptools' `find_packages` looks for packages (dir with `__init__.py` module)](https://pythonhosted.org/setuptools/setuptools.html#using-find-packages), and the `pytest_profiling.py` module should probably be specified in a `py_modules` argument to `setup.py`:

```
py_modules=['pytest_profiling'],
```

To get over this I either fix `setup.py` or manually copy `pytest_profiling.py` module to my virtualenv `site-packages` dir.

---
## More trouble

Now that the plugin runs, I see the "prof/" dir is created; however, nothing appears in it.

```
$ PYTHONPATH=. py.test /Users/pavel/project/tests/test_report.py --profile-svg -vv
=============================================== test session starts ================================================
platform darwin -- Python 2.7.10 -- py-1.4.30 -- pytest-2.7.2 -- /Users/pavel/.venvs/project/bin/python
rootdir: /Users/pavel/project/src, inifile:
plugins: profiling
collected 7 items

tests/test_report.py::TestReport::test_ignored PASSED
tests/test_report.py::TestReport::test_disabled <- /Users/pavel/project/tests/__init__.py PASSED

============================================= 7 passed in 1.50 seconds =============================================

$ ls -la1 prof/
.
..
```

This happens when I run `py.test` with both `--profile-svg` and `--profile` arguments.

**Comment by eeaston** [comment]
Hi there, thanks for raising this.  I'm in the process of fixing all the setup files and getting this all up on PyPI - I'll make sure to look at this issue along the way.

**Comment by eeaston** [comment]
Hi there - are you still having issues? If so, could you send me an example test that isn't creating the profile data?

**Comment by asfaltboy** [comment]
The pypi version install nice and easy. By the way, have you considered moving the plugins to ["pytest-dev" org](https://github.com/pytest-dev)?

Unfortunately, `prof/` folder is still not being populated, and I can see no output regarding Profiling. I'll try to find time later to debug it.

**Comment by jguenther** [comment]
I'm having the same issue (`pytest_pyfunc_call` is never being called). I ran pytest with `--debug` and `--trace-config` and this plugin does seem to be enabled, and the rest of the hooks are being called.

One odd thing is that under the `active plugins` section of the config trace output, I see:

```
    4380641104          : <pytest_profiling.Profiling object at 0x1051b4750>
```

I'm not sure why the name of this plugin isn't correct here (I'd have expected the first column to be `profiling` or something similar) or if it has anything to do with this issue though.

**Comment by Daenyth** [comment]
I'm also seeing `prof` empty with `platform linux2 -- Python 2.7.6, pytest-2.8.7, py-1.4.31, pluggy-0.3.1`

**Comment by eeaston** [comment]
Hi guys - can you send me an example test case that isn't creating the profile directory? I'll close otherwise as this is a very old ticket now.

**Comment by eeaston** [comment]
Closing as cannot-reproduce for now, happy to have another look if people are still having issues.
