### ISSUE TITLE
Hanging indefinitely on `s.bind` in base.py

### ISSUE THREAD

**Issue by Daenyth** [manahl/pytest-plugins#44]
Using 1.2.5, when I run my tests, the library hangs indefinitely on s.bind. I rolled back to 1.2.4 and it works. I'm fairly sure what's happening is that binding to a random IP doesn't work on OSX.
https://github.com/manahl/pytest-plugins/blob/master/pytest-server-fixtures/pytest_server_fixtures/base.py#L43

**Comment by eeaston** [comment]
Hi @bmoscon, any chance you could have a look at this one?

**Comment by bmoscon** [comment]
@eeaston this is the same issue I emailed/forwarded you some weeks ago. I can take a look once I get my mac (we dont all have them yet)

**Comment by eeaston** [comment]
Ok thanks I'll take a look

**Comment by Daenyth** [comment]
This is still a problem, I'm hitting it again in writing #50 

It's fixed for me by changing to `host = '127.0.0.1'`.

I know you're using circleci already, but you might consider using travis - they offer builds on both linux and macos at the same time, where circle's docs imply you have to pick one or the other

**Comment by bmoscon** [comment]
I'm not sure if @eeaston has taken a look yet. If not, I have a mac now and can take a look

**Comment by Daenyth** [comment]
It would be really nice to have a full version release including the fix. I'd like to update past 1.2.4

**Comment by bmoscon** [comment]
New version came out last week:

https://pypi.python.org/pypi/pytest-server-fixtures

**Comment by Daenyth** [comment]
Oh cool, I didn't see it - I was looking at the latest commit of setup.py, didn't realize you kept the version number elsewhere
