### ISSUE TITLE
SVG file not created with pytest-profiling

### ISSUE THREAD

**Issue by exhuma** [manahl/pytest-plugins#46]
When adding `--profile-svg` I can see profiling output, but the SVG file is not created:

    [...]
            1    0.003    0.003    0.007    0.007 configparser.py:988(_read)
            1    0.000    0.000    0.002    0.002 model.py:102(get_connection)
            1    0.001    0.001    0.001    0.001 {built-in method _sqlite3.connect}
           33    0.001    0.000    0.001    0.000 configparser.py:1216(__init__)

    SVG profile in /home/users/malbert/work/pynet/prof/combined.svg.

    =============================================== 27 tests deselected =========================================================                                                  ===================================== 1 passed, 27 deselected in 1.62 seconds ===============================================

    malbert@BBS-nexus16 ~/work/pynet>  stat /home/users/malbert/work/pynet/prof/combined.svg
    stat: cannot stat '/home/users/malbert/work/pynet/prof/combined.svg': No such file or directory

I've tried to run the commands  manually and it works:

    malbert@BBS-nexus16 ~/work/pynet> ./env/bin/gprof2dot -f pstats prof/combined.prof | dot -T png > profile.png
    malbert@BBS-nexus16 ~/work/pynet> stat profile.png
      File: 'profile.png'
      Size: 397962          Blocks: 784        IO Block: 262144 regular file
    Device: 2dh/45d Inode: 528452      Links: 1
    Access: (0664/-rw-rw-r--)  Uid: ( 1000/ malbert)   Gid: ( 1000/ malbert)
    Access: 2017-03-01 16:54:47.725468478 +0100
    Modify: 2017-03-01 16:58:32.505460439 +0100
    Change: 2017-03-01 16:58:32.505460439 +0100
     Birth: -
    malbert@BBS-nexus16 ~/work/pynet> ./env/bin/gprof2dot -f pstats prof/combined.prof | dot -Tsvg > profile.svg
    malbert@BBS-nexus16 ~/work/pynet> stat profile.svg
      File: 'profile.svg'
      Size: 91601           Blocks: 184        IO Block: 262144 regular file
    Device: 2dh/45d Inode: 528453      Links: 1
    Access: (0664/-rw-rw-r--)  Uid: ( 1000/ malbert)   Gid: ( 1000/ malbert)
    Access: 2017-03-01 16:55:35.737466761 +0100
    Modify: 2017-03-01 16:58:48.909459852 +0100
    Change: 2017-03-01 16:58:48.909459852 +0100
     Birth: -

**Comment by exhuma** [comment]
Found the issue: If the virtual-environment is not activated the command `gprof2dot` is not found. It seems like pytest-profile needs it to be in `PATH`.

Would be nice if it also worked if the test-script is executed directly via `/path/to/env/bin/pytest [...]` without having to activate the environment.

**Comment by eeaston** [comment]
Good spot, we'll have a look.

**Comment by eeaston** [comment]
@exhuma Hi, this should be fixed now can you check?
