### ISSUE TITLE
pytest-profiling  does not profile fixtures

### ISSUE THREAD

**Issue by lafrech** [manahl/pytest-plugins#48]
Consider the following example:

```python
import pytest


@pytest.fixture()
def work_func_fix():
    s = 0
    for i in range(1000):
        s += i * i
    return s


def work_func_test():
    s = 0
    for i in range(1000):
        s += i * i
    return s


def test_example(work_func_fix):
    assert work_func_fix == work_func_test()
```

Apparently, only `test_example` is profiled. `work_func_test` appears in the profiling results, but `work_func_fix` does not.

Is it a design choice? I've been searching but found no reference to that. Or is there a flag I should pass to enable fixture profiling?

We use pytest to test a Flask application. Fixtures create the database, and instantiate and initialize the application. We'd like to profile the initialization process but it does not appear in the results.

In fact, the profiling result in my example above shows a lot of things I don't care about (everything that is not under `test_example`), but not the fixture I do care about.

**Comment by lafrech** [comment]
I do get the fixtures profiled with this change:

```python
     @pytest.hookimpl(hookwrapper=True)
-    def pytest_runtest_call(self, item):
+    def pytest_runtest_protocol(self, item, nextitem):
         prof_filename = os.path.abspath(os.path.join("prof", clean_filename(item.name) + ".prof"))
         prof = cProfile.Profile()
         prof.enable()
```

This is probably obvious to the devs. I suppose the choice of using `pytest_runtest_call` was deliberate.

Do you consider my use case invalid? Could `pytest_runtest_protocol` be used, at least with an opt-in argument?

**Comment by bmoscon** [comment]
I couldn't say. @eeaston might know

**Comment by bmoscon** [comment]
@eeaston what do you think?

**Comment by bmoscon** [comment]
looking over the documentation, I think the change would actually be fine. `pytest_runtest_call` simply executes the test `item` whereas pytest_runtest_protocol calls the setup, test, then tear down and the associated hooks. 

I think we can safely change this @eeaston but it will mean the behavior would change. I think its behavior we want, but I wanted to double check and see what you thought.

**Comment by jeremyqa** [comment]
Any update on this issue?

**Comment by mehdisadeghi** [comment]
I am getting different results when I profile with `cProfile` and `pytest --profile`. Since I use fixtures, I think that is due to this issue. Can somebody explain why pytest-profling skips fixtures? In my case I use caching in my fixture to run subsequent tests faster.

**Comment by eeaston** [comment]
Hi @lafrech  - thanks for raising this and it's definitely a valid use case.  There's a number of issues with the profiling that I'm working through at the moment and I'll cover this as well.
Your example implementation is good - we need to get the profiler turned on early enough to cover fixture execution.
