### ISSUE TITLE
pytest-shutil uses /bin in tests which fails on Fedora hosts

### ISSUE THREAD

**Issue by nirik** [manahl/pytest-plugins#67]
The tests for pytest-shutil uses a test where it does a chdir to /bin then checks to make sure it's in /bin. 

Unfortunately this fails on Fedora hosts as /bin is a link to /usr/bin, so the test shows it's in the wrong dir: 

=================================== FAILURES ===================================
__________________________________ test_chdir __________________________________
    def test_chdir():
        here = os.getcwd()
        with cmdline.chdir('/bin'):
>           assert os.getcwd() == '/bin'
E           AssertionError: assert '/usr/bin' == '/bin'
E             - /usr/bin
E             + /bin
tests/integration/test_cmdline_integration.py:9: AssertionError

I suggest using /etc ? Doing that here locally makes the tests pass...

**Comment by bmoscon** [comment]
server-fixtures uses the __init__ to define paths, maybe we should do that for this fixture so on different hosts it can be changed

**Comment by bmoscon** [comment]
@eeaston

**Comment by eeaston** [comment]
I'll update the test to use a tempdir instead.

**Comment by eeaston** [comment]
Fixed in 932be1da7890b4a159118204107bb506d7ef6bcc, thanks for raising!
