### ISSUE TITLE
Add copy of MIT license to pypi archives?

### ISSUE THREAD

**Issue by nirik** [manahl/pytest-plugins#68]
I realize there's a copy of the license in this repo, but it might be nice if you could also include it in releases of each of the component packages on pypi. Since I am packaging some of these things up for Fedora and Fedora wants a copy of the license (if available) in each package. 

Thanks for your consideration.

**Comment by eeaston** [comment]
Good idea @nirik !

**Comment by eeaston** [comment]
This is fixed now, thanks for raising :)
