### ISSUE TITLE
[virtualenv] Specify python version

### ISSUE THREAD

**Issue by abravalheri** [manahl/pytest-plugins#88]
Dear maintainers, thank you very much for creating and maintaining such a handy plugin! It really helps a lot to write functional/integration tests!

I just would like to clarify a doubt: is it possible to specify the version of the python used inside the virtualenv?

For example, would it be possible to use the feature to run commands using 2.7, while running pytest itself under 3.4?

**Comment by jcfr** [comment]
Great question.

The `virtualenv` fixture accepts a `python` and `args` arguments, this should allows you to achieve what you described.

See https://github.com/manahl/pytest-plugins/blob/e58de699eee1a1059f2fbc0093a04f5464f1613c/pytest-virtualenv/pytest_virtualenv.py#L43-L48

@eeaston I suggest you close this issue.

**Comment by eeaston** [comment]
Thanks @jcfr  - yup that's the way to do it.
